version: 2

sphinx:
  configuration: docs/source/conf.py

formats: all

python:
  version: 3.6
  install:
    - requirements: docs/torch_for_docs.txt
    - method: pip
      path: .
      extra_requirements:
        - doc
