#See link below for available options
#https://docs.readthedocs.io/en/stable/config-file/

version: 2

sphinx:
  configuration: docs/source/conf.py

formats:
  - htmlzip
  - epub

python:
  version: 3.6
  install:
    - requirements: docs/requirements-rtd.txt
    - method: pip
      path: .
