version: 2

sphinx:
  configuration: docs/source/conf.py

formats: all

python:
  version: 3.6
  install:
    - requirements: docs/rtd_torch_requirements.txt
    - method: pip
      path: .
    - requirements: requirements-doc.txt
