# Generated by Django 2.2.4 on 2019-08-30 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("app", "0001_initial")]

    operations = [
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("docfile", models.FileField(upload_to="media")),
            ],
        ),
        migrations.DeleteModel(name="Content"),
    ]
