# Generated by Django 2.2.4 on 2019-08-30 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("app", "0002_auto_20190830_1730")]

    operations = [
        migrations.CreateModel(
            name="Content",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("content_Main_Img", models.ImageField(upload_to="images")),
                ("style_Main_Img", models.ImageField(upload_to="images")),
            ],
        ),
        migrations.DeleteModel(name="Document"),
    ]
