# Generated by Django 2.2.5 on 2019-09-09 20:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [("app", "0003_auto_20190830_1838")]

    operations = [
        migrations.RemoveField(model_name="content", name="content_Main_Img"),
        migrations.RemoveField(model_name="content", name="name"),
        migrations.RemoveField(model_name="content", name="style_Main_Img"),
        migrations.AddField(
            model_name="content",
            name="file",
            field=models.ImageField(
                default=django.utils.timezone.now, upload_to="media"
            ),
            preserve_default=False,
        ),
    ]
