# Generated by Django 2.2.5 on 2019-09-09 22:20

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [("app", "0004_auto_20190909_2230")]

    operations = [
        migrations.RenameField(
            model_name="content", old_name="file", new_name="contentFile"
        ),
        migrations.AddField(
            model_name="content",
            name="styleFile",
            field=models.ImageField(
                default=datetime.datetime(2019, 9, 9, 22, 20, 46, 18277, tzinfo=utc),
                upload_to="media",
            ),
            preserve_default=False,
        ),
    ]
