name: docs

on:
  repository_dispatch:
    types:
      - docs-build

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up python
        uses: actions/setup-python@v2
        with:
          python-version: 3.6

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Upgrade or install additional system packages
        run: pip install --upgrade pip setuptools virtualenv wheel

      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install dev requirements
        run: pip install -r requirements-dev.txt

      - name: Create environment
        run: tox -e docs-html --no-test

      - name: Build documentation

        env:
          PYSTICHE_DOWNLOAD_GALLERY: False
          # TODO: remove this when this workflow has access to a GPU
          PYSTICHE_PLOT_GALLERY: False
        run: tox -e docs-html

      - name: Zip galleries
        working-directory: docs/source
        run: |
          git rev-parse HEAD > galleries/commit
          zip -r main.zip galleries

      - name: Upload galleries
        uses: appleboy/scp-action@v0.1.1
        with:
          host: pystiche.org
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          source: main.zip
          target: ${{ secrets.SERVER_TARGET }}/galleries
