name: docs

on:
  pull_request:
    paths:
      - ".cirun.yml"
      - ".github/workflows/docs-build.yml"

  repository_dispatch:
    types:
      - docs-build

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Set up Python
        uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: 3.6
          miniconda-version: latest

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Upgrade or install additional system packages
        run: pip install --upgrade pip setuptools virtualenv wheel

      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install dev requirements
        run: pip install -r requirements-dev.txt

      - name: Create environment
        run: tox -e docs-html --notest

      - name: Build documentation
        env:
          PYSTICHE_DOWNLOAD_GALLERY: False
          PYSTICHE_PLOT_GALLERY: True
        run: tox -e docs-html

      - name: Zip galleries
        working-directory: docs/source
        run: |
          git rev-parse HEAD > galleries/commit
          zip -r main.zip galleries

      - name: Upload galleries
        uses: appleboy/scp-action@v0.1.1
        with:
          host: pystiche.org
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          source: docs/source/main.zip
          strip_components: 2
          target: ${{ secrets.SERVER_TARGET }}/galleries
